# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: swift

before_install:
  - gem install xcpretty

matrix:
  include:
  - name: "Xcode 11.3.1 iOS 12.4 iPhone 6"
    osx_image: xcode11.3
    env: DESTINATION='platform=iOS Simulator,name=iPhone 6,OS=12.4' UI=true
  - name: "Xcode 11.3.1 iOS 13.3 iPhone 8"
    osx_image: xcode11.3
    env: DESTINATION='platform=iOS Simulator,name=iPhone 8,OS=13.3' UI=true
  - name: "Xcode 12 iOS 14 iPhone 8"
    osx_image: xcode12
    env: DESTINATION='platform=iOS Simulator,name=iPhone 8,OS=14.0' UI=true

script:
- set -o pipefail
- travis/validate_carthage.sh
- xcodebuild -destination "$DESTINATION" -workspace Example/XCTest-Gherkin.xcworkspace -scheme XCTest-Gherkin-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO test | xcpretty -f `xcpretty-gherkin-formatter/bin/xcpretty-gherkin-formatter`
- if [ $UI ]; then xcodebuild -destination "$DESTINATION" -workspace Example/XCTest-Gherkin.xcworkspace -scheme XCTest-Gherkin-Example-UI -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO test | xcpretty -f `xcpretty-gherkin-formatter/bin/xcpretty-gherkin-formatter`; fi
- bundle exec pod lib lint --allow-warnings
